### PR TITLE
Change Effect Selector to a Select

### PR DESCRIPTION
**Pull request by nathanfiscus**
Provides a list of options rather than requiring numeric input.

### CODE REVIEW

**Comment by nathanfiscus** [comment]
I didn't test this yet.  But don't see a reason why this wouldn't work.

**Comment by kreene1987** [comment]
Great idea! Will test.

**Comment by kreene1987** [comment]
Select returns a string. Thoughts on ways to convert to a number? I can test when I get home.

**Comment by nathanfiscus** [comment]
Thought that it might do that. We just need to add a {{ value | int }}  not sure if you can do that directly with a !input or if we need to add a variable that converts it.

**Pull request merged**
